### ISSUE TITLE
Column Sorting

### ISSUE THREAD

**Issue by TruckDye** [BlinkVonDoom/fuzeCallboard#15]
I'm not able to determine why the tables are sorting the way they are. Ideally I'd love it to sort by time in current status, if that's not possible then alphabetical or total number of calls taken.

**Comment by BlinkVonDoom** [comment]
@TruckDye which would you say is preference on the sorting

Time (optimal)
Alphabetical (2nd)
Call taken  (3rd choice ?)

**Comment by TruckDye** [comment]
Time would be ideal.
